obligarcy/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static, settings

urlpatterns = [
    # ex: /oblicarcy/
    url(r'^$', views.index, name='index'),
    url(r'^firehose/$', views.firehose, name='firehose'),


    url(r'^profile/$', views.profile, name='profile'),
    # ex: /obligarcy/user/5/
    url(r'^user/([0-9]+)/$', views.show_prof, name='user'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^update/$', views.update_profile, name='update'),
    # ex: /obligarcy/user
    #url(r'^user/$', views.profile, name='profile'),

    # ex: /oblicarcy/submissions/5/
    url(r'^submission/([0-9a-z]+)/$', views.show_sub, name='submission'),
    url(r'^submit/([0-9a-z]+)/([0-9]+)/$', views.submit, name='submit'),
    url(r'^upload/([0-9a-z]+)/([0-9]+)/$', views.submit_upload, name='upload'),

#    url(r'^submit/([0-9a-z]+)/([0-9]+)/$', views.submit, name='submit'),

    # ex: /oblicarcy/contracts/5/
    url(r'^contract/([0-9a-z]+)/$', views.show_con, name='contract'),
    url(r'^challenge/$', views.challenge, name='challenge'),
    url(r'^sign/([0-9a-z]+)/$', views.sign_con, name='sign'),
    url(r'^active/([0-9]+)/$', views.show_active, name='active'),

    # ex: /oblicarcy/login/
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reality/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^obligarcy/', include('obligarcy.urls')),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^obligarcy/', include('obligarcy.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

obligarcy/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

#from django.utils import timezone


def pkgen():
    from hashlib import sha1
    from random import random
    pk = sha1(str(random()).encode('utf-8')).hexdigest().lower()[:6]
    return pk


# Activity Streams
# TODO: Add Action on deadline expire
# TODO: Fix Create Action Method
class Action(models.Model):
    actor = models.ForeignKey(User, related_name='actions', db_index=True)
    verb = models.CharField(max_length=255)
    target_ct = models.ForeignKey(ContentType, blank=True, null=True,
                                    related_name='target_obj')
    target_id = models.SlugField(null=True, blank=True,
                                                db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):              # __unicode__ or str
        string_action = self.actor.username + " " + self.verb
        if self.target:
            string_action += " " + str(self.target)[:15]
        return string_action


# The default user constructor is:
#
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, null=True) #   OneToOneField(User)
    # The additional attributes we wish to include.
    website = models.URLField(null=True)
    picture = ThumbnailerImageField(upload_to='profile_images', null=True)
    location = models.CharField(max_length=20, null=True)
    bio = models.CharField(max_length=144, null=True)
    follows = models.ManyToManyField('UserProfile', related_name='followed_by')

    def str(self):
        return self.user.username


class Submission(models.Model):
    id = models.CharField(max_length=6, primary_key=True, default=pkgen, unique=True)
    body = models.CharField(max_length=200, null=True)
    media = ThumbnailerImageField(upload_to='submissions/%Y/%m/%d', null=True)
    pub_date = models.DateTimeField('submitted')
    user = models.ForeignKey(User)
    is_media = models.BooleanField(default=False)
    licence = models.CharField(max_length=30, null=True)
    # This Generic Relation allows backward Queries from Contract/Dl etc.
    activities = GenericRelation(Action, related_query_name='activities',
                                    object_id_field="target_id",
                                    content_type_field='target_ct')
    # Word Count
    # FILE

    def __str__(self):
        if not self.is_media:
            return self.body
        elif self.is_media:
            return "This is "+ user.username +"\'s Media Submission"

# Add active
class Contract(models.Model):
    id = models.CharField(max_length=6, primary_key=True, default=pkgen, unique=True)
    title = models.CharField(max_length=60, null=True)
    conditions = models.CharField(max_length=400, null=True)
    small_print = models.CharField(max_length=200, null=True)
    start_date = models.DateTimeField('start date')
    end_date = models.DateTimeField('end date')
    frequency = models.CharField(max_length=2, default='O')
    is_active = models.BooleanField(default=False)
    open_sign = models.BooleanField(default=False)
    users = models.ManyToManyField(User) # signee
    submissions = models.ManyToManyField(Submission)
    completed_by = models.ManyToManyField(User, related_name='has_completed')
    # This Generic Relation allows backward Queries from Contract/Dl etc.
    activities = GenericRelation(Action, related_query_name='activities',
                                    object_id_field="target_id",
                                    content_type_field='target_ct')

    def __str__(self):              # __unicode__ or str
        return self.title

# add a signee for the
class Deadline(models.Model):
    deadline = models.DateTimeField('deadline') #DateTimeField makes the sub form not accept
    submission = models.ForeignKey(Submission, null=True) # This has got to be many and many
    contract = models.ForeignKey(Contract)
    signee = models.ForeignKey(User)
    is_accomplished = models.BooleanField(default=False)
    is_late = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)
    # This Generic Relation allows backward Queries from Contract/Dl etc.
    activities = GenericRelation(Action, related_query_name='activities',
                                    object_id_field="target_id",
                                    content_type_field='target_ct')


    def __str__(self):              # __unicode__ or str
        string_deadline = self.deadline.strftime("%A %-d %b %Y")
        return string_deadline

obligarcy/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Submission, Contract, Deadline, UserProfile, Action
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.urlresolvers import reverse as rev

from jinja2 import Environment

from .forms import UserForm, UserProfileForm
from .forms import ContractForm, SubForm, UploadForm
from .control import completeContract, activeContract, activeContracts
from .control import checkEligibility, expireDeadlines, create_action
from .control import get_stream
from django.utils import timezone
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout

import pandas as pd
from datetime import datetime
import time
import json


def environment(**options):
    env = Environment(**options)
    env.globals.update({
       'static': staticfiles_storage.url,
       'url': rev,
    })
    # add easy-thumbnails function as a Jinja2 filter
    from easy_thumbnails.templatetags.thumbnail import thumbnail_url
    env.filters.update(**{
        'thumbnail_url': thumbnail_url,
    })
    from easy_thumbnails.templatetags.thumbnail import thumbnail
    env.filters.update(**{
        'thumbnail': thumbnail,
    })
    from crispy_forms.templatetags.crispy_forms_filters import as_crispy_form
    def crispy(form):
        return as_crispy_form(form, 'Bootstrap3', form.helper.label_class, form.helper.field_class)
    def reverse_list(list):
        return reversed(list)
    def time_until(deadline):
        until = deadline.deadline - timezone.now()
        time_until = str(until.days)
        return time_until
    def time_since(pub_date):
        difference = timezone.now() - pub_date
        if difference >= timedelta(days=1):
            return '%(time)s days ago' % {'time': difference.days}
        elif difference <= timedelta(minutes=1):
            return 'just now'
        elif difference <= timedelta(days=1):
            return '%(time)s hours %(minute)s minutes ago' % {'time': difference.seconds//3600, 'minute': difference.seconds//60}#td.seconds//3600, (td.seconds//60)%60
    env.globals.update(**{'time_since':time_since})
    env.globals.update(**{'time_until':time_until})
    env.filters.update(**{'crispy':crispy,})
    env.filters.update(**{'reverse_list':reverse_list})
    return env



def index(request):
    activity_feed = Action.objects.all()
    activity_label = 'Recent Activity'
    return render(request, 'obligarcy/index.html',
         {'activity_feed': activity_feed, 'activity_label':activity_label})


##########################
# User Views
##########################
def register(request):
    registered = False
    errors = ""
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        #print((profile_form.location))
        #print((profile_form))
        if profile_form.is_valid():
            print(('yup'))
        if user_form.is_valid():# and profile_form.is_valid()
            user = user_form.save()
            pswd = user.password # for immediate log in
            user.set_password(user.password)
            user.save()
            # DO profile attributes, OneToOneField with User
            # Form somereason saving the form doesnt work. profile form won't validate
            profile = UserProfile(bio=request.POST['bio'], location=request.POST['location'], user=user)
            #profile = profile_form.save(commit=False)
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            create_action(user, 'created an account')
            registered = True
            u = authenticate(username=user.username, password=pswd)
            login(request, u)
            request.session['username'] = user.username
            request.session['id'] = user.id
            return HttpResponseRedirect('/profile/')
        else:
            errors = str(user_form.errors)#, profile_form.errors
    user_form = UserForm()
    profile_form = UserProfileForm()
    return render(request, 'obligarcy/register.html',
         {'user_form': user_form, 'profile_form': profile_form,
         'errors':errors})


def user_login(request):
    status = "Type your login details in below..."
    next_url = ""
    if request.GET:
        next_url = request.GET['next']
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:# Is the account active? It could have been disabled.
                login(request, user)
                request.session['username'] = user.username
                request.session['id'] = user.id
                if next_url == "":
                    return HttpResponseRedirect('/profile/')
                else:
                    return HttpResponseRedirect(next_url)
            else:
                status = "Your account is not active, please contact the site admin."
        else:
            # Bad login details were provided. So we can't log the user in.
            # print(("Invalid login details: {0}, {1}".format(username, password)))
            status = "Your username and/or password were incorrect."
    # The request is unsuccessful as HTTP POST, so display the login form.
    return render(request, 'obligarcy/login.html',
                {'next':next_url, 'status':status})

@login_required
def user_logout(request):
    logout(request)
    request.session['username'] = None
    request.session['id'] = None
    return HttpResponseRedirect('/')

# TODO: Add Prochaine Deadlines
@login_required
def profile(request):
    user_id = request.session['id']
    user = get_object_or_404(User, id=user_id)
    #print((user.userprofile.picture.path))
    posts = user.submission_set.all()
    contracts = user.contract_set.all()
    deadlines = Deadline.objects.filter(signee=user,
        is_expired=False, is_accomplished=False).order_by('deadline')
    # Active Contracts
    map(activeContract, contracts)
    active_contracts = []
    for con in contracts:
        if con.is_active:
            if not user in con.completed_by.all():
                active_contracts.append(con)
    # Completed Contracts
    completed_contracts = []
    for c in contracts:
        if user in c.completed_by.all():
            completed_contracts.append(c)
    # Get Follows and followed_by
    follows = user.userprofile.follows.all()
    followed_by = user.userprofile.followed_by.all() # followed_by.user
    stream = get_stream(user)
    activity_label = 'You are following..'
    return render(request, 'obligarcy/profile.html',
        {'contracts': contracts, 'posts': reversed(posts), 'profile': user,
        'completed':completed_contracts, 'deadlines':deadlines,
        'follows':follows, 'followed_by':followed_by,
        'can_follow':False, 'already_follows': False,
        'active':active_contracts, 'stream':stream, 'activity_label':activity_label})

@login_required
def show_prof(request, user_id):
    browser = User.objects.get(id=request.session['id'])
    user = get_object_or_404(User, id=user_id)
    posts = user.submission_set.all()
    contracts = user.contract_set.all()
    deadlines = Deadline.objects.filter(signee=user,
        is_expired=False, is_accomplished=False).order_by('deadline')
    # Active Contracts
    map(activeContract, contracts)
    active_contracts = []
    for con in contracts:
        if con.is_active:
            if not user in con.completed_by.all():
                active_contracts.append(con)
    # Completed Contracts
    completed_contracts = []
    for c in contracts:
        if user in c.completed_by.all():
            completed_contracts.append(c)
    # Get Follows and followed_by
    follows = user.userprofile.follows.all()
    followed_by = user.userprofile.followed_by.all() # followed_by.user
    # Following
    can_follow = False
    already_follows = False
    if int(user_id) != int(request.session['id']):
        can_follow = True
    if browser.userprofile in followed_by:
        already_follows = True
    stream = Action.objects.filter(actor=user)
    activity_label = user.username + '\'s Recent Activity'
    return render(request, 'obligarcy/profile.html',
        {'contracts': contracts, 'posts': reversed(posts), 'profile': user,
        'completed':completed_contracts, 'deadlines':deadlines,
        'follows':follows, 'followed_by':followed_by,
        'can_follow':can_follow, 'already_follows': already_follows,
        'active':active_contracts, 'stream':stream, 'activity_label':activity_label})


def follow(request):
    if request.method == 'POST':
        user_id = request.POST.get('id')
        action = request.POST.get('action')
        if user_id and action:
            try:
                target = User.objects.get(id=user_id)
                actor = User.objects.get(id=request.session['id'])
                if action == 'follow':
                    actor.userprofile.follows.add(target.userprofile)
                    actor.save()
                    create_action(actor, 'followed', target)

                else:
                    actor.userprofile.follows.remove(target.userprofile)
                    actor.save()
                return JsonResponse({'status':'ok'})

obligarcy/templates/obligarcy/active.html
{% extends "obligarcy/base.html" %}

{% block content %}
<style>
.media-body{
  width:auto;
}
</style>
<div class='row'>
  <div class='col-md-12'>
    {% if contracts %}
        <div class="panel panel-default">
          <div class="panel-body">
            <div class='panel-heading'>Active Contracts</div>
            <table class='table table-hover'>
              <tr>
                <th>Contract</th>
                <th>Deadlines</th>
                <th>Signees</th>
                <th></th>
              </tr>
        {% for contract in contracts %}
              <tr>
                <td><a href="/contract/{{ contract.id }}/">{{ contract.title }}</a>
                </td>
                <td>
                  <small>Final Deadline:</small> {{ contract.end_date.strftime('%y/%m/%d %A')}}<br>
                  <small>Next Deadline:</small> {{ contract.deadline_set.filter(is_expired=False, is_accomplished=False).first().deadline.strftime('%y/%m/%d %A')}}<br>
                  <small>Time Remaining:</small> {{ time_until(contract.deadline_set.filter(is_expired=False, is_accomplished=False).first()) }} days<br>
                </td>
                <td>
                  {% for u in contract.users.all() %}
                  {% if u.userprofile.picture %}
                    <div class="media">
                      <div class="media-left">
                        <a href="/user/{{ u.id }}/">
                          <img class="media-object img-rounded" src="/media/{{ u.userprofile.picture['feed']}}" alt="Problem serving picture"/>
                        </a>
                      </div>
                      <div class="media-body">
                        <h5 class="media-heading"><a href="/user/{{ u.id }}/">{{ u.username }}</a></h5>
                        {{ u.userprofile.bio }}
                      </div>
                    </div>
                  {% else %}
                  <h5><a href="/user/{{ u.id }}/">{{ u.username }}</a></h5>
                  {{ u.userprofile.bio }}
                  {% endif %}
                  {% endfor %}
                </td>
                <td><a class='btn btn-default' href="/submit/{{ contract.id }}/{{user.id}}/">Submit</a>
                </td>
              </tr>
        {% endfor %}
            </table>
          </div>
        </div>
    {% else %}<br>
        <h3>Nothing To Report</h3>
        <a href={{ url('challenge')}} >Draft</a> a new contract.<br>
        View contracts seeking signatures.
    {% endif %}
  </div>
</div>
{% endblock content %}

obligarcy/templates/obligarcy/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Exchange of obligations">
    <meta name="author" content="Fenimore">
    <link rel="icon" href="../../favicon.ico">

    <title>Muse</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css">
<link href='https://fonts.googleapis.com/css?family=Raleway:400,400italic,700italic' rel='stylesheet' type='text/css'>
<style>

/* unvisited link */
a:link {
    color: #673ab7;
}

/* visited link */
a:visited {
    color: #7c4dff;
}

/* mouse over link */
a:hover {
    color: #9c27b0;
    text-decoration: none;
}

/* selected link */
a:active {
    color: #673ab7;
}

.dropdown span{
  color: #536DFE;
}

.navbar-default{
  background-color:#F8F8FF;
  color: #E1BEE7;
}

#id_input {
  height: auto;
}
    .container {
      margin-right: 15px;
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    ul a {
        display: block;
        width:100%;
    }
    ul a:hover {
        text-decoration: none;
    }
    .navbar-right {
      margin-right: 24%;
    }

    #deadline_list{
        width: 100%;
        height: auto;
        max-height: 115px;
        overflow: auto;
    }
    .stream-box{
      height:auto;
      max-height:200px;
      overflow: auto;
      width:50%;
    }

    html {
      position: relative;
      min-height: 100%;
    }
    body {
      /* Margin bottom by footer height */
      margin-bottom: 60px;
      background-color: #FEFEFA;
      font-family: 'Raleway', sans-serif;
    }
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      /* Set the fixed height of the footer here */
      height: 50px;
    }
    .nav table {
      color: black;
    }

    a.btn-danger, a.btn-info, a.btn-primary, a.btn-success{
      color:white;
    }

</style>


<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
$(document).ready(function() {
    $('.datepicker').datepicker();
    $(".nav li.disabled a").click(function() {
      return false;
    });
});
$('#myTab a').click(function (e) {
    if($(this).parent('li').hasClass('active')){
        $( $(this).attr('href') ).hide();
    }
    else {
        e.preventDefault();
        $(this).tab('show');
    }
});

// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
</script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Muse</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{url('index')}}#about">About</a></li>
            <li><a href="{{url('firehose')}}">Firehose</a></li>
            {% if user.is_authenticated() %}
            <li><a href="{{url('profile')}}">Dashboard</a></li>
            {% else %}
            <li><a href="{{url('register')}}">Sign Up</a></li>
            {% endif %}
          </ul>


          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated() %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li> Next Deadline</li>
                  <table class="table table-hover">
                    <tr>
                      <td>
                        {% if user.contract_set.all() %}
                          {% if user.deadline_set.filter(is_expired=False).all() %}
                            <a href="/submit/{{ user.deadline_set.filter(is_expired=False).order_by('deadline').first().contract.id }}/{{ user.id }}">
                              {{ user.deadline_set.filter(is_expired=False, is_accomplished=False).order_by('deadline').first() }}</a> Deadline in
                              {{ time_until(user.deadline_set.filter(is_expired=False, is_accomplished=False).order_by('deadline').first()) }} days
                          {% endif %}
                        {% endif %}
                      </td>
                    </tr>
                  </table>
                  <li>Follows</li>
                  <table class="table table-hover">
                    {% for u in user.userprofile.follows.all() %}
                      <tr>
                        <td>
                          <div class="media">
                            <div class="media-left">
                              <a href="/user/{{ u.user.id }}">
                                {% if u.picture %}
                                <img src=/media/{{ u.picture['feed']}}
                                class="img-responsive img-circle" alt="Problem Serving Image">
                                {% endif %}
                              </a>
                            </div>
                            <div class="media-body">
                              <h5 class="media-heading"><a href="/user/{{ u.user.id }}">{{ u.user.username}}</a></h5>
                              {{ u.bio[:12] }}
                            </div>
                          </div>
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                  <li><a href="/logout">Logout</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/challenge"><span class="glyphicon glyphicon-export" aria-hidden="true"></span> Challenge</a></li>
                    <li><a href="/active/{{user.id}}"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> Submit</a></li>
                  </ul>
              </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/profile/"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.username }} Profile</a></li>
                  <li><a href="/active/{{ user.id }}"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span> Active Contracts</a></li>
                  <li class='disabled'><a href="#"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Legacy Contracts</a></li>
                  <li class='disabled'><a href="#"><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Contacts</a></li>
                  <li><a href="/challenge"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Challenge</a></li>
                  <li role="separator" class="divider"></li>
                  <li class='disabled'><a href="#"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings</a></li>
                  <li><a href="/logout">Logout</a></li>
                  <li class="dropdown-header"><a href="{{url('index')}}#about">Help</a></li>
                </ul>
              </li>
              {% else %}
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Welcome!
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href={{url('register')}}>Sign Up</a></li>
                    <li><a href={{url('login')}}>Login</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header"><a href="{{url('index')}}#about">Help</a></li>
                  </ul>
                </li>
                {% endif %}


          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row" style="padding-top:60px">

        <div class="col-sm-9 col-md-9 col-md-offset-3" style='margin-left:5px;margin-right:10px;'>
                {% block content %}{% endblock %}
        </div>
        <div>
          {% block side_block %}{% endblock %}
        </div>
      </div>
      <br>
      <br>
      <br>
    </div><!-- /.container -->
    <footer class="footer">
      <div class="container">
        <p class="text-muted"> Muse | 2015-2016 |
           <a href='{{url('index')}}#about'>About</a> <a href='{{url('register')}}'>Register</a> <a href={{url('login')}}>Login</a> <a href={{url('logout')}}>Logout</a></p>
      </div>
    </footer>
  </body>
</html>

obligarcy/templates/obligarcy/login.html
{% extends "obligarcy/base.html" %}

{% block content %}
<div class='row'>
  <div class='col-md-5'>
        <h1>Login</h1>
        <hr>
        <div class='well' >{{ status }}</div>
        {% if next %}
        <form id="login_form" method="post" action="/login/?next={{next}}">
        {%else%}
        <form id="login_form" method="post" action="/login/">
        {% endif %}
            {% csrf_token %}
            Username: <input class="form-control" type="text" name="username" value="" size="50" />
            <br />
            Password: <input class="form-control" type="password" name="password" value="" size="50" />
            <br />

            <input class='btn btn-default' type="submit" value="Login" />
        </form>
        Dont have an account yet? <a href={{ url('register')}}>Sign Up</a><br>

  </div>
</div>
{% endblock content %}